### ISSUE TITLE
Brainbrowser v 2.5.2 has issues loading minc files from some scanners

### ISSUE THREAD

**Issue by MounaSafiHarab** [aces/brainbrowser#332]
Tested on the brainbrowser website (volume viewer). Loading the minc file directly does not work and gives the error below:
"Sorry, this does not look like a NetCDF file."
Loading the header and raw files work without a problem.
The file comes from a Philips scanner.

p.s: I am using a dcm2mnc binary provided to me by @rdvincent (that solves issues with GE and philips scanners we have encountered in the past) to generate the minc files (in case this info is of relevance).

**Comment by rdvincent** [comment]
@MounaSafiHarab This is probably an HDF5 file using some new feature or version that the existing HDF5 reader doesn't support. Can you send me an example?

**Comment by MounaSafiHarab** [comment]
@rdvincent 

Sure. I will send a separate e-mail to you with details of where I placed some example files.
Thanks!

**Comment by rdvincent** [comment]
@MounaSafiHarab Hi, I have looked at this problem and it seems to have been fixed after 2.5.2 was released. Perhaps @natacha-beck could make a 2.5.3? I think this commit is probably the one that fixed the issue: 662e23c4e4a5bcf111a2b6d0e9fc7d53626db31c

**Comment by natacha-beck** [comment]
@rdvincent and @MounaSafiHarab just done a minor release 2.5.3 that include this fix. 

But Mouna still have issue: 

> so the new brainbrowser fixed the viewing of almost all files
> except the DTI ones still issue the same error for me
> so all anatomical (t1, t2) and all fMRI are good

**Comment by MounaSafiHarab** [comment]
I have put 2 dti sample files that still have this issue in a directory that I will send you the path for in an email.

**Comment by rdvincent** [comment]
@MounaSafiHarab @natacha-beck Thanks I should be able to look at it soon.

**Comment by natacha-beck** [comment]
@MounaSafiHarab @bert I star to take a look to this issue, Apparently it is a HDF5 file but BrainBrowser failed to find the xspace, ysapce and zspace (I can get this information with mincinfo). Then it try to read the file as a NetCDF and failed since it is a HDF5.

**Comment by rdvincent** [comment]
@natacha-beck @MounaSafiHarab I have added a commit to my fork that should fix these files, I will do a pull request soon.

**Comment by MounaSafiHarab** [comment]
thanks @rdvincent @natacha-beck 

problem resolved in 2.5.4!
